### PR TITLE
Suppress superfluous logging when the message is the same

### PR DESCRIPTION
**Pull request by jaraco**
This commit adds some throttling around the repeated log output when the message is the same.

### CODE REVIEW

**Comment by jaraco** [comment]
I'm happy to help maintain this package as well if you'll grant the necessary access.

**Comment by tabo** [comment]
Just gave you admin/owner access to bitbucket/github/pypi :)

**Comment by jaraco** [comment]
!thanks tabo

**Comment by tabo** [comment]
!cheer

**Pull request merged**
